### ISSUE TITLE
can you release your trained model

### ISSUE THREAD

**Issue by LinJM** [wwjwhen/Watch-Attend-and-Spell-tensorflow-version#1]

**Comment by wwjwhen** [comment]
Thanks for your interest in my work! This work was uploaded after my internship in MSRA and sorry for not saving a well-trained model. And I think the model is not very hard to reproduce, so I just release the codes without saved parameters. You can run the model by following README, and if any problem, feel free to contact me!

**Comment by LinJM** [comment]
I use your code to train the model, but it can't get a well result.
![image](https://user-images.githubusercontent.com/5347113/44316967-369f6980-a461-11e8-84b1-11736f622773.png)

**Comment by LinJM** [comment]
BTW，When I run `model-single-GPU.py`， I encounter a error : 
line 500, in get_sample
    next_p, next_w, next_state, next_alpha_past = session.run([p, w, h, alpha], feed_dict=input_dict)
TypeError: Fetch argument 47 has invalid type <type 'numpy.int64'>, must be a string or Tensor. (Can not convert a int64 into a Tensor or Operation.)
----------
So I change the get_sample() function's code, I am not sure if my modification is correct.

**Comment by wwjwhen** [comment]
well, seems strange,  what's your batch size?

**Comment by LinJM** [comment]
Batch Size is 3.

**Comment by wwjwhen** [comment]
OK, I will have a check on the codes and batch size affects the performance heavily I suggest you to set it to  2 or 4 if your GPU memory is limited instead of odd number.

**Comment by LinJM** [comment]
hello @wwjwhen， Any progress? I use another repo's code can get exp rate 0.33.

**Comment by wwjwhen** [comment]
Temporarily I have no access to GPU sources and I test my codes without GPU, I run the codes in main function directly without invoking main() function and the batch_size is 2, the process runs as expected.  Maybe you can run the codes in main() function directly after modifying the path on GPU and observe the performance.  BTW, distributed version gets lower ExpRate due to batch size and batchnorm, because of too many paddings when aligning data.
