### ISSUE TITLE
'anno' not defined

### ISSUE THREAD

**Issue by ravijakhania13** [wwjwhen/Watch-Attend-and-Spell-tensorflow-version#4]
Hi mate,
I converted your code into jupyter notebook. I tried running it and after some updates in epoch 0, it gave error that 'anno' is not defined in the get_sample() function. Could you please help me with this issue?

**Comment by wwjwhen** [comment]
I  think it is caused by the version of tensorflow, high version may cause unexpected problemsSent from my Huawei Mobile-------- Original Message --------Subject: [SPAM] [wwjwhen/Watch-Attend-and-Parse-tensorflow-version] 'anno' not defined (#4)From: Ravi Jakhania To: wwjwhen/Watch-Attend-and-Parse-tensorflow-version CC: Subscribed Hi mate,
I converted your code into jupyter notebook. I tried running it and after some updates in epoch 0, it gave error that 'anno' is not defined in the get_sample() function. Could you please help me with this issue?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wwjwhen/Watch-Attend-and-Parse-tensorflow-version","title":"wwjwhen/Watch-Attend-and-Parse-tensorflow-version","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/wwjwhen/Watch-Attend-and-Parse-tensorflow-version"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"'anno' not defined (#4)"}],"action":{"name":"View Issue","url":"https://github.com/wwjwhen/Watch-Attend-and-Parse-tensorflow-version/issues/4"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wwjwhen/Watch-Attend-and-Parse-tensorflow-version/issues/4",
"url": "https://github.com/wwjwhen/Watch-Attend-and-Parse-tensorflow-version/issues/4",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
